sudo: required
services:
    - docker


before_install:
    - docker build -t osuarez/travis-ci-testing -f Dockerfile.dev .

script:
    - docker run osuarez/travis-ci-testing npm run test -- --coverage
    